name: Recompile and Release Minecraft 1.8.9 (MCP)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  recompile-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'temurin'

    - name: Recompile using MCP
      run: |
        ./runtime/bin/python2.7 runtime/recompile.py
        
    - name: Compress recompiled binaries
      run: |
        zip -r recompiled-minecraft.zip reobf/*

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: v1.8.9-recompiled
        release_name: Minecraft 1.8.9 Recompiled
        draft: false
        prerelease: false
        files: recompiled-minecraft.zip
        
